export type CategoryId =
  | "poultry"
  | "beef"
  | "ready-meals"
  | "appetizers";

export type Product = {
  id: string;
  category: CategoryId;
  name: string;
  nameEn: string;
  description: string;
  descriptionEn?: string;
  unit: string;
  unitEn: string;
  image?: string;
  price: number;
  featured?: boolean;
  spicy?: boolean;
};

export const categories: {
  id: CategoryId;
  label: string;
  labelEn: string;
  image: string;
  note?: string;
  noteEn?: string;
}[] = [
  {
    id: "poultry",
    label: "دواجن",
    labelEn: "Poultry",
    image: "/assets/jahez/poultry.jpg",
    note: "البيع بالكيلو الكامل — مجهز ومتبل وجاهز للتسوية",
    noteEn: "Sold by the full kilogram — prepared, seasoned and ready to cook",
  },
  {
    id: "beef",
    label: "لحوم",
    labelEn: "Beef",
    image: "/assets/jahez/beef.jpg",
    note: "البيع بالكيلو الكامل — تجهيز يومي حسب الطلب",
    noteEn: "Sold by the full kilogram — prepared fresh for each order",
  },
  {
    id: "ready-meals",
    label: "وجبات جاهزة",
    labelEn: "Ready Meals",
    image: "/assets/jahez/ready-meals.jpg",
    note: "اختاري الصنف بالحجم ووحدة البيع الموضحة",
    noteEn: "Order using the listed tray or kilogram unit",
  },
  {
    id: "appetizers",
    label: "مقبلات",
    labelEn: "Appetizers",
    image: "/assets/jahez/appetizers.jpg",
    note: "العبوة تحتوي على 15 قطعة",
    noteEn: "Each pack contains 15 pieces",
  },
];

export const products: Product[] = [
  {
    id: "chicken-fajita",
    category: "poultry",
    name: "فاهيتا دجاج",
    nameEn: "Chicken Fajita",
    description: "شرائح دجاج متبلة بنكهة الفاهيتا وجاهزة للتسوية.",
    descriptionEn: "Seasoned chicken strips prepared in fajita style and ready to cook.",
    unit: "كيلو كامل",
    unitEn: "Full kg",
    price: 450,
    featured: true,
    image: "/assets/jahez/hero-chicken.jpg",
  },
  {
    id: "chicken-curry",
    category: "poultry",
    name: "دجاج بالكاري",
    nameEn: "Chicken Curry",
    description: "قطع دجاج متبلة بالكاري ومجهزة لوجبة سريعة بطعم غني.",
    descriptionEn: "Curry-seasoned chicken prepared for a quick, flavorful meal.",
    unit: "كيلو كامل",
    unitEn: "Full kg",
    price: 450,
  },
  {
    id: "oregano-chicken-fillet",
    category: "poultry",
    name: "فيليه دجاج أوريجانو",
    nameEn: "Oregano Chicken Fillet",
    description: "فيليه دجاج متبل بالأوريجانو والبهارات وجاهز للشوي أو الطهي.",
    descriptionEn: "Chicken fillet seasoned with oregano and spices, ready to grill or cook.",
    unit: "كيلو كامل",
    unitEn: "Full kg",
    price: 450,
    featured: true,
  },
  {
    id: "breaded-chicken",
    category: "poultry",
    name: "تشيكن بانيه",
    nameEn: "Breaded Chicken",
    description: "شرائح دجاج بانيه متبلة ومجهزة للقلي أو التسوية في الفرن.",
    descriptionEn: "Seasoned breaded chicken slices ready to fry or oven-cook.",
    unit: "كيلو كامل",
    unitEn: "Full kg",
    price: 500,
  },
  {
    id: "tandoori-chicken",
    category: "poultry",
    name: "دجاج تندوري",
    nameEn: "Tandoori Chicken",
    description: "دجاج متبل بخليط تندوري متوازن وجاهز للتسوية.",
    descriptionEn: "Chicken seasoned with a balanced tandoori blend and ready to cook.",
    unit: "كيلو كامل",
    unitEn: "Full kg",
    price: 450,
  },
  {
    id: "crispy-chicken",
    category: "poultry",
    name: "كريسبي دجاج",
    nameEn: "Crispy Chicken",
    description: "قطع دجاج كريسبي متبلة ومجهزة للقلي.",
    descriptionEn: "Seasoned crispy chicken pieces prepared for frying.",
    unit: "كيلو كامل",
    unitEn: "Full kg",
    price: 450,
  },
  {
    id: "shish-tawook",
    category: "poultry",
    name: "شيش طاووق",
    nameEn: "Shish Tawook",
    description: "مكعبات دجاج متبلة بتتبيلة شيش طاووق وجاهزة للشوي.",
    descriptionEn: "Chicken cubes in a shish tawook marinade, ready to grill.",
    unit: "كيلو كامل",
    unitEn: "Full kg",
    price: 440,
  },
  {
    id: "hot-nashville-chicken",
    category: "poultry",
    name: "هوت ناشفيل تشيكن",
    nameEn: "Hot Nashville Chicken",
    description: "دجاج متبل بنكهة ناشفيل الحارة ومجهز للقلي.",
    descriptionEn: "Chicken seasoned with a hot Nashville-style blend and ready to fry.",
    unit: "كيلو كامل",
    unitEn: "Full kg",
    price: 450,
    spicy: true,
  },
  {
    id: "beef-shawarma",
    category: "beef",
    name: "شاورما لحم",
    nameEn: "Beef Shawarma",
    description: "شرائح لحم متبلة بتتبيلة الشاورما وجاهزة للتسوية.",
    descriptionEn: "Beef strips seasoned in shawarma style and ready to cook.",
    unit: "كيلو كامل",
    unitEn: "Full kg",
    price: 750,
    featured: true,
  },
  {
    id: "kofta",
    category: "beef",
    name: "كفتة",
    nameEn: "Kofta",
    description: "كفتة متبلة ومشكلة وجاهزة للشوي أو الطهي.",
    descriptionEn: "Seasoned shaped kofta ready to grill or cook.",
    unit: "كيلو كامل",
    unitEn: "Full kg",
    price: 680,
  },
  {
    id: "beef-burger",
    category: "beef",
    name: "برجر لحم",
    nameEn: "Beef Burger",
    description: "برجر لحم متبل ومشكل وجاهز للتسوية.",
    descriptionEn: "Seasoned beef burger patties prepared and ready to cook.",
    unit: "كيلو كامل",
    unitEn: "Full kg",
    price: 630,
  },
  {
    id: "mini-burger",
    category: "beef",
    name: "ميني برجر",
    nameEn: "Mini Burger",
    description: "قطع ميني برجر لحم مناسبة للوجبات السريعة والعائلية.",
    descriptionEn: "Mini beef burger patties suited for quick family meals.",
    unit: "كيلو كامل",
    unitEn: "Full kg",
    price: 630,
  },
  {
    id: "soy-ginger-beef",
    category: "beef",
    name: "لحم صويا وجنزبيل",
    nameEn: "Soy & Ginger Beef",
    description: "شرائح لحم متبلة بالصويا والجنزبيل وجاهزة للطهي السريع.",
    descriptionEn: "Beef strips marinated with soy and ginger, ready for quick cooking.",
    unit: "كيلو كامل",
    unitEn: "Full kg",
    price: 750,
  },
  {
    id: "beef-teriyaki",
    category: "beef",
    name: "بيف ترياكي",
    nameEn: "Beef Teriyaki",
    description: "شرائح لحم بتتبيلة ترياكي متوازنة وجاهزة للتسوية.",
    descriptionEn: "Beef strips in a balanced teriyaki marinade, ready to cook.",
    unit: "كيلو كامل",
    unitEn: "Full kg",
    price: 750,
  },
  {
    id: "spicy-cajun-beef",
    category: "beef",
    name: "بيف كاجن حار",
    nameEn: "Spicy Cajun Beef",
    description: "شرائح لحم متبلة بالكاجن الحار وجاهزة للتسوية.",
    descriptionEn: "Beef strips in a spicy Cajun seasoning, ready to cook.",
    unit: "كيلو كامل",
    unitEn: "Full kg",
    price: 750,
    spicy: true,
  },
  {
    id: "sweet-chili-beef",
    category: "beef",
    name: "بيف سويت تشيلي",
    nameEn: "Sweet Chili Beef",
    description: "شرائح لحم بتتبيلة سويت تشيلي وجاهزة للطهي.",
    descriptionEn: "Beef strips in a sweet chili marinade, ready to cook.",
    unit: "كيلو كامل",
    unitEn: "Full kg",
    price: 750,
  },
  {
    id: "beef-bolognese",
    category: "beef",
    name: "صوص بولونيز باللحم",
    nameEn: "Beef Bolognese Sauce",
    description: "صوص بولونيز باللحم مطهي وجاهز للتسخين والتقديم مع المكرونة.",
    descriptionEn: "Cooked beef bolognese sauce, ready to heat and serve with pasta.",
    unit: "كيلو كامل",
    unitEn: "Full kg",
    price: 550,
    featured: true,
  },
  {
    id: "stuffed-vine-leaves",
    category: "ready-meals",
    name: "ورق عنب محشي",
    nameEn: "Stuffed Vine Leaves",
    description: "ورق عنب محشي ومجهز حسب الطلب.",
    descriptionEn: "Stuffed vine leaves prepared to order.",
    unit: "كيلو كامل",
    unitEn: "Full kg",
    price: 260,
    featured: true,
    image: "/assets/jahez/ready-meals.jpg",
  },
  {
    id: "beef-goulash",
    category: "ready-meals",
    name: "جلاش باللحم",
    nameEn: "Beef Goulash",
    description: "صينية جلاش محشية باللحم ومجهزة للتسوية.",
    descriptionEn: "A tray of beef-filled goulash prepared and ready to bake.",
    unit: "صينية",
    unitEn: "Tray",
    price: 470,
  },
  {
    id: "lasagna",
    category: "ready-meals",
    name: "لازانيا",
    nameEn: "Lasagna",
    description: "صينية لازانيا مجهزة للتسوية والتقديم.",
    descriptionEn: "A prepared lasagna tray ready to bake and serve.",
    unit: "صينية",
    unitEn: "Tray",
    price: 600,
  },
  {
    id: "bechamel-pasta",
    category: "ready-meals",
    name: "مكرونة بشاميل",
    nameEn: "Bechamel Pasta",
    description: "صينية مكرونة بشاميل مجهزة للتسوية.",
    descriptionEn: "A prepared bechamel pasta tray ready to bake.",
    unit: "صينية",
    unitEn: "Tray",
    price: 600,
  },
  {
    id: "vegetable-spring-rolls",
    category: "appetizers",
    name: "سبرينج رول خضار",
    nameEn: "Vegetable Spring Rolls",
    description: "سبرينج رول بحشوة خضار، مجهز للقلي.",
    descriptionEn: "Vegetable-filled spring rolls prepared for frying.",
    unit: "عبوة 15 قطعة",
    unitEn: "Pack of 15 pcs",
    price: 180,
    image: "/assets/jahez/appetizers.jpg",
  },
  {
    id: "chicken-spring-rolls",
    category: "appetizers",
    name: "سبرينج رول دجاج",
    nameEn: "Chicken Spring Rolls",
    description: "سبرينج رول بحشوة دجاج، مجهز للقلي.",
    descriptionEn: "Chicken-filled spring rolls prepared for frying.",
    unit: "عبوة 15 قطعة",
    unitEn: "Pack of 15 pcs",
    price: 200,
  },
  {
    id: "beef-sambousek",
    category: "appetizers",
    name: "سمبوسك لحم",
    nameEn: "Beef Sambousek",
    description: "سمبوسك بحشوة لحم، مجهز للقلي أو الخَبز.",
    descriptionEn: "Beef-filled sambousek prepared for frying or baking.",
    unit: "عبوة 15 قطعة",
    unitEn: "Pack of 15 pcs",
    price: 200,
  },
  {
    id: "cheese-sambousek",
    category: "appetizers",
    name: "سمبوسك جبنة",
    nameEn: "Cheese Sambousek",
    description: "سمبوسك بحشوة جبنة، مجهز للقلي أو الخَبز.",
    descriptionEn: "Cheese-filled sambousek prepared for frying or baking.",
    unit: "عبوة 15 قطعة",
    unitEn: "Pack of 15 pcs",
    price: 150,
  },
  {
    id: "chicken-sambousek",
    category: "appetizers",
    name: "سمبوسك دجاج",
    nameEn: "Chicken Sambousek",
    description: "سمبوسك بحشوة دجاج، مجهز للقلي أو الخَبز.",
    descriptionEn: "Chicken-filled sambousek prepared for frying or baking.",
    unit: "عبوة 15 قطعة",
    unitEn: "Pack of 15 pcs",
    price: 200,
  },
];

export const productFallbacks: Record<CategoryId, string> = {
  poultry: "/assets/jahez/poultry.jpg",
  beef: "/assets/jahez/beef.jpg",
  "ready-meals": "/assets/jahez/ready-meals.jpg",
  appetizers: "/assets/jahez/appetizers.jpg",
};

export function formatPrice(price: number) {
  return `${new Intl.NumberFormat("en-US", {
    maximumFractionDigits: 0,
  }).format(price)} ج.م`;
}
